import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const translations = {
  en: {
    navbar: {
      home: 'Home',
      policies: 'Policies',
      howItWorks: 'How It Works',
      faq: 'FAQ',
      contact: 'Contact',
      profile: 'Profile',
      dashboard: 'Dashboard',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
    },
    home: {
      heroTitle: '🌾 Smart Crop Insurance for Modern Farmers',
      heroSubtitle: 'Weather-based insurance powered by blockchain technology',
      exploreBtn: 'Explore Policies',
      getStartedBtn: 'Get Started',
      whyChoose: 'Why Choose InsuChain?',
      whyChooseSubtitle: 'Revolutionary insurance solutions for farmers',
      decentralized: 'Decentralized',
      decentralizedDesc: 'Smart contracts ensure transparent and automatic payouts based on real weather data.',
      realtimeData: 'Real-Time Data',
      realtimeDataDesc: 'Live weather monitoring from OpenWeatherMap API for accurate coverage triggers.',
      instantPayouts: 'Instant Payouts',
      instantPayoutsDesc: 'Automated payouts when weather conditions trigger claims - no waiting, no paperwork.',
      secure: 'Secure',
      secureDesc: 'Built on blockchain with cryptographic security for maximum protection.',
      easyToUse: 'Easy to Use',
      easyToUseDesc: 'Simple registration and policy management through our user-friendly platform.',
      affordable: 'Affordable',
      affordableDesc: 'Competitive premiums with transparent pricing and no hidden charges.',
      howItWorks: 'How It Works',
      howItWorksSubtitle: 'Simple 4-step process to protect your crops',
      step1Register: '1. Register',
      step1RegisterDesc: 'Create an account and verify your details as a farmer.',
      step2Choose: '2. Choose Policy',
      step2ChooseDesc: 'Select a policy that matches your crop and location needs.',
      step3Purchase: '3. Purchase',
      step3PurchaseDesc: 'Complete the purchase on blockchain with transparent transaction.',
      step4GetPaid: '4. Get Paid',
      step4GetPaidDesc: 'Automatic payout when weather triggers your insurance claim.',
      readyToProtect: 'Ready to Protect Your Farm?',
      joinFarmers: 'Join thousands of farmers using InsuChain for weather insurance',
      startToday: 'Start Today',
      viewPolicies: 'View Policies',
    },
    policies: {
      title: '🛡️ Insurance Policies',
      subtitle: 'Choose the best protection plan for your farm',
      premium: 'Premium',
      payout: 'Payout',
      rainfallThreshold: '🌧️ Rainfall Threshold',
      temperatureRange: '🌡️ Temperature Range',
      coverage: 'Coverage',
      coverageDesc: 'Automatically triggered when weather conditions match the policy thresholds.',
      purchaseBtn: 'Purchase Policy',
      purchasing: 'Purchasing...',
      loginToPurchase: 'Login to Purchase',
      notAvailable: 'Not Available',
      noPolicies: 'No policies available at the moment. Please check back later.',
      confirmPurchase: 'Purchase this policy for',
    },
    auth: {
      loginTitle: 'Welcome Back',
      registerTitle: 'Create Account',
      emailLabel: 'Email Address',
      emailPlaceholder: 'your@email.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'Confirm Password',
      loginBtn: 'Login',
      registerBtn: 'Register',
      switchToRegister: "Don't have an account? Register",
      switchToLogin: 'Already have an account? Login',
      roleLabel: 'I am a:',
      farmer: 'Farmer',
      admin: 'Admin',
      walletLabel: 'Wallet Address (Optional)',
      walletPlaceholder: '0x...',
      walletHint: 'You can add this later in your profile',
      passwordMismatch: 'Passwords do not match',
      loginSuccess: 'Login successful! Redirecting...',
      registerSuccess: 'Registration successful! Redirecting...',
      loginFailed: 'Login failed. Please try again.',
      registerFailed: 'Registration failed. Please try again.',
    },
    profile: {
      myProfile: 'My Profile',
      adminDashboard: 'Admin Dashboard',
      myPolicies: 'My Policies',
      myTransactions: 'My Transactions',
      totalPolicies: '📊 Total Policies Available',
      totalPoliciesSold: '🛒 Total Policies Sold',
      totalUsers: '👥 Total Users',
      farmers: '🌾 Farmers',
      admins: '⚙️ Admins',
      totalPayouts: '💰 Total Payouts',
      usersList: 'Users List',
      id: 'ID',
      email: 'Email',
      role: 'Role',
      walletAddress: 'Wallet Address',
      joined: 'Joined',
    },
    dashboard: {
      title: '📊 Admin Dashboard',
      subtitle: 'Manage policies and users',
      policyManagement: 'Policy Management',
      createPolicy: 'Create New Policy',
      createPolicyBtn: 'Create Policy',
      cancel: 'Cancel',
      policyName: 'Policy Name',
      premiumETH: 'Premium (ETH)',
      payoutETH: 'Payout (ETH)',
      policyCreated: 'Policy created successfully!',
      allUsers: 'All Users',
    },
    footer: {
      description: 'Decentralized weather-based insurance for farmers using blockchain technology.',
      quickLinks: 'Quick Links',
      support: 'Support',
      followUs: 'Follow Us',
      terms: 'Terms & Conditions',
      copyright: 'All rights reserved. Built with ❤️ for farmers.',
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      logout: 'Logout',
      english: 'English',
      hindi: 'हिंदी',
    },
  },
  hi: {
    navbar: {
      home: 'होम',
      policies: 'नीतियाँ',
      howItWorks: 'कैसे काम करता है',
      faq: 'अक्सर पूछे जाने वाले प्रश्न',
      contact: 'संपर्क',
      profile: 'प्रोफाइल',
      dashboard: 'डैशबोर्ड',
      login: 'लॉगिन',
      register: 'रजिस्टर',
      logout: 'लॉगआउट',
    },
    home: {
      heroTitle: '🌾 किसानों के लिए स्मार्ट फसल बीमा',
      heroSubtitle: 'ब्लॉकचेन तकनीक द्वारा संचालित मौसम-आधारित बीमा',
      exploreBtn: 'नीतियों का अन्वेषण करें',
      getStartedBtn: 'शुरुआत करें',
      whyChoose: 'InsuChain को क्यों चुनें?',
      whyChooseSubtitle: 'किसानों के लिए क्रांतिकारी बीमा समाधान',
      decentralized: 'विकेंद्रीकृत',
      decentralizedDesc: 'स्मार्ट अनुबंध वास्तविक मौसम डेटा के आधार पर पारदर्शी और स्वचालित भुगतान सुनिश्चित करते हैं।',
      realtimeData: 'वास्तविक समय डेटा',
      realtimeDataDesc: 'OpenWeatherMap API से लाइव मौसम निगरानी सटीक कवरेज ट्रिगर के लिए।',
      instantPayouts: 'तत्काल भुगतान',
      instantPayoutsDesc: 'जब मौसम की स्थितियां दावों को ट्रिगर करती हैं तो स्वचालित भुगतान - कोई प्रतीक्षा नहीं, कोई कागजी कार्रवाई नहीं।',
      secure: 'सुरक्षित',
      secureDesc: 'क्रिप्टोग्राफिक सुरक्षा के साथ ब्लॉकचेन पर निर्मित अधिकतम सुरक्षा के लिए।',
      easyToUse: 'उपयोग में आसान',
      easyToUseDesc: 'हमारे उपयोगकर्ता के अनुकूल प्लेटफॉर्म के माध्यम से सरल पंजीकरण और नीति प्रबंधन।',
      affordable: 'सशक्त',
      affordableDesc: 'प्रतिस्पर्धी प्रीमियम पारदर्शी मूल्य निर्धारण के साथ और कोई छिपी हुई शुल्क नहीं।',
      howItWorks: 'कैसे काम करता है',
      howItWorksSubtitle: 'आपकी फसलों की रक्षा के लिए सरल 4-चरणीय प्रक्रिया',
      step1Register: '1. रजिस्टर करें',
      step1RegisterDesc: 'एक खाता बनाएं और किसान के रूप में अपने विवरण को सत्यापित करें।',
      step2Choose: '2. नीति चुनें',
      step2ChooseDesc: 'एक नीति चुनें जो आपकी फसल और स्थान की जरूरतों से मेल खाती हो।',
      step3Purchase: '3. खरीदें',
      step3PurchaseDesc: 'पारदर्शी लेनदेन के साथ ब्लॉकचेन पर खरीदारी पूरी करें।',
      step4GetPaid: '4. भुगतान प्राप्त करें',
      step4GetPaidDesc: 'जब मौसम आपके बीमा दावे को ट्रिगर करता है तो स्वचालित भुगतान।',
      readyToProtect: 'अपने खेत की रक्षा के लिए तैयार हैं?',
      joinFarmers: 'मौसम बीमा के लिए InsuChain का उपयोग करने वाले हजारों किसानों में शामिल हों',
      startToday: 'आज शुरू करें',
      viewPolicies: 'नीतियाँ देखें',
    },
    policies: {
      title: '🛡️ बीमा नीतियाँ',
      subtitle: 'अपने खेत के लिए सर्वोत्तम सुरक्षा योजना चुनें',
      premium: 'प्रीमियम',
      payout: 'भुगतान',
      rainfallThreshold: '🌧️ वर्षा थ्रेशोल्ड',
      temperatureRange: '🌡️ तापमान रेंज',
      coverage: 'कवरेज',
      coverageDesc: 'जब मौसम की स्थितियां नीति थ्रेशोल्ड से मेल खाती हैं तो स्वचालित रूप से ट्रिगर होता है।',
      purchaseBtn: 'नीति खरीदें',
      purchasing: 'खरीद रहे हैं...',
      loginToPurchase: 'खरीदने के लिए लॉगिन करें',
      notAvailable: 'उपलब्ध नहीं',
      noPolicies: 'इस समय कोई नीति उपलब्ध नहीं है। बाद में फिर से जांचें।',
      confirmPurchase: 'यह नीति खरीदें',
    },
    auth: {
      loginTitle: 'स्वागत है',
      registerTitle: 'खाता बनाएं',
      emailLabel: 'ईमेल पता',
      emailPlaceholder: 'your@email.com',
      passwordLabel: 'पासवर्ड',
      passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'पासवर्ड की पुष्टि करें',
      loginBtn: 'लॉगिन',
      registerBtn: 'रजिस्टर',
      switchToRegister: 'खाता नहीं है? रजिस्टर करें',
      switchToLogin: 'पहले से खाता है? लॉगिन करें',
      roleLabel: 'मैं हूँ:',
      farmer: 'किसान',
      admin: 'प्रशासक',
      walletLabel: 'वॉलेट पता (वैकल्पिक)',
      walletPlaceholder: '0x...',
      walletHint: 'आप इसे बाद में अपनी प्रोफाइल में जोड़ सकते हैं',
      passwordMismatch: 'पासवर्ड मेल नहीं खाते',
      loginSuccess: 'लॉगिन सफल! रीडायरेक्ट किया जा रहा है...',
      registerSuccess: 'पंजीकरण सफल! रीडायरेक्ट किया जा रहा है...',
      loginFailed: 'लॉगिन विफल। कृपया फिर से कोशिश करें।',
      registerFailed: 'पंजीकरण विफल। कृपया फिर से कोशिश करें।',
    },
    profile: {
      myProfile: 'मेरी प्रोफाइल',
      adminDashboard: 'व्यवस्थापक डैशबोर्ड',
      myPolicies: 'मेरी नीतियाँ',
      myTransactions: 'मेरे लेनदेन',
      totalPolicies: '📊 कुल नीतियाँ उपलब्ध',
      totalPoliciesSold: '🛒 कुल नीतियाँ बेची गई',
      totalUsers: '👥 कुल उपयोगकर्ता',
      farmers: '🌾 किसान',
      admins: '⚙️ प्रशासक',
      totalPayouts: '💰 कुल भुगतान',
      usersList: 'उपयोगकर्ताओं की सूची',
      id: 'आईडी',
      email: 'ईमेल',
      role: 'भूमिका',
      walletAddress: 'वॉलेट पता',
      joined: 'शामिल हुए',
    },
    dashboard: {
      title: '📊 व्यवस्थापक डैशबोर्ड',
      subtitle: 'नीतियों और उपयोगकर्ताओं को प्रबंधित करें',
      policyManagement: 'नीति प्रबंधन',
      createPolicy: 'नई नीति बनाएं',
      createPolicyBtn: 'नीति बनाएं',
      cancel: 'रद्द करें',
      policyName: 'नीति का नाम',
      premiumETH: 'प्रीमियम (ETH)',
      payoutETH: 'भुगतान (ETH)',
      policyCreated: 'नीति सफलतापूर्वक बनाई गई!',
      allUsers: 'सभी उपयोगकर्ता',
    },
    footer: {
      description: 'ब्लॉकचेन तकनीक का उपयोग करके किसानों के लिए विकेंद्रीकृत मौसम-आधारित बीमा।',
      quickLinks: 'त्वरित लिंक',
      support: 'समर्थन',
      followUs: 'हमारा अनुसरण करें',
      terms: 'नियम और शर्तें',
      copyright: 'सभी अधिकार सुरक्षित। ❤️ किसानों के लिए निर्मित।',
    },
    common: {
      loading: 'लोड हो रहा है...',
      error: 'त्रुटि',
      success: 'सफलता',
      logout: 'लॉगआउट',
      english: 'English',
      hindi: 'हिंदी',
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = translations[language];

  const toggleLanguage = () => {
    setLanguage(language === 'en' ? 'hi' : 'en');
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
